# Direct Method

In [1]:
import numpy as np
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [3]:
A = np.array([[3,0,0],[0,2,0],[0,0,7]])
b = np.array([4,8,21])
x = np.zeros(3)
for i in range(3):
    x[i] = b[i] / A[i,i]
print(x)

[1.33333333 4.         3.        ]


In [4]:
x[0], x[1], x[2] ## remember indexing starts with 0

(1.3333333333333333, 4.0, 3.0)

In [5]:
def solvediag(A,b):
    n=len(b)
    x = np.zeros(n)
    for i in range(n):
        x[i] = b[i] / A[i,i]
    return x

In [6]:
print(A)
print(b)

[[3 0 0]
 [0 2 0]
 [0 0 7]]
[ 4  8 21]


In [7]:
solvediag(A,b)

array([1.33333333, 4.        , 3.        ])

In [8]:
A2 = np.array([[0,0,0],[0,2,0],[0,0,7]])
b2 = np.array([4,8,21])
solvediag(A2,b2)

/var/folders/7h/m_gp7w0x1955xv6xvcndpkf40000gn/T/ipykernel_7879/84374609.py:5: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = b[i] / A[i,i]


array([inf,  4.,  3.])

In [9]:
A2 = np.array([[4,0,0],[0,2,0],[0,0,7]])
b2 = np.array([4,8,21,3])
solvediag(A2,b2)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [10]:
np.shape(A) # this function returns the shape of an array

(3, 3)

In [14]:
def solvediag(A,b):
    n=len(b)
    if np.shape(A) != (n,n):
        print("solvediag is only defined for a square A whose size matches")
        return
    x = np.zeros(n)
    for i in range(n):
        x[i] = b[i] / A[i,i]
    return x

In [15]:
solvediag(A2,b2)

solvediag is only defined for a square A whose size matches


In [16]:
solvediag(A,b)

array([1.33333333, 4.        , 3.        ])

In [17]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.diagonal(B) # returns the entries on the diagonal of any matrix

array([1, 5, 9])

In [19]:
np.diag([1,2,3,4,5,6]) # makes a diagonal matrix with the given entries along th

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [20]:
np.diag(np.diagonal(B))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [21]:
print(B)
print(B - np.diag(np.diagonal(B)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [22]:
print(A)
print(A - np.diag(np.diagonal(A)))

[[3 0 0]
 [0 2 0]
 [0 0 7]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
np.count_nonzero(A) ## counts the number of nonzero entries

3

In [ ]:
def solvediag(A,b):
    n=len(b)
    if np.shape(A) != (n,n):
        print("solvediag is only defined for a square A whose size matches 
        return
    if np.count_nonzero(A-np.diag(np.diagonal(A))) != 0:
        print("solvediag is only defined for a diagonal matrix A")
        return
    x = np.zeros(n)
    for i in range(n):
    x[i] = b[i] / A[i,i]
    return x